<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'krishna',
	'db_password' => 'lovesradha',
	'db_server_version' => '5.5.54-MariaDB-1ubuntu0.14.04.1',
	'mailer_from_name' => 'REAL MILK India',
	'mailer_from_email' => 'srinib@realmilk.co.in',
	'mailer_transport' => 'smtp',
	'mailer_host' => 'smtp.gmail.com',
	'mailer_port' => '465',
	'mailer_user' => 'srinib@acknotech.com',
	'mailer_password' => 'acknotech007',
	'mailer_encryption' => 'ssl',
	'mailer_auth_mode' => 'login',
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '88d1a314ef22933e667864fcbf618308b87a0ac09db0f25d3c578430716fdb08',
	'site_url' => 'http://34.199.143.107/mautic/index.php',
	'webroot' => null,
	'cache_path' => '/var/www/html/mautic/app/cache',
	'log_path' => '/var/www/html/mautic/app/logs',
	'image_path' => 'media/images',
	'tmp_path' => '/var/www/html/mautic/app/cache',
	'theme' => 'coffee',
	'locale' => 'en_US',
	'dev_hosts' => null,
	'trusted_hosts' => array(

	),
	'trusted_proxies' => array(

	),
	'rememberme_key' => '926bc5702e7327c362aba0cd125a7a945c527c84',
	'rememberme_lifetime' => '31536000',
	'rememberme_path' => '/',
	'rememberme_domain' => null,
	'default_pagelimit' => 100,
	'default_timezone' => 'Asia/Kolkata',
	'date_format_full' => 'F j, Y g:i a T',
	'date_format_short' => 'D, M d',
	'date_format_dateonly' => 'F j, Y',
	'date_format_timeonly' => 'g:i a',
	'ip_lookup_service' => 'maxmind_download',
	'ip_lookup_auth' => null,
	'ip_lookup_config' => array(

	),
	'update_stability' => 'stable',
	'cookie_path' => '/',
	'cookie_domain' => null,
	'cookie_secure' => null,
	'cookie_httponly' => 0,
	'do_not_track_ips' => array(

	),
	'do_not_track_bots' => array(
		"0" => "MSNBOT", 
		"1" => "msnbot-media", 
		"2" => "bingbot", 
		"3" => "Googlebot", 
		"4" => "Google Web Preview", 
		"5" => "Mediapartners-Google", 
		"6" => "Baiduspider", 
		"7" => "Ezooms", 
		"8" => "YahooSeeker", 
		"9" => "Slurp", 
		"10" => "AltaVista", 
		"11" => "AVSearch", 
		"12" => "Mercator", 
		"13" => "Scooter", 
		"14" => "InfoSeek", 
		"15" => "Ultraseek", 
		"16" => "Lycos", 
		"17" => "Wget", 
		"18" => "YandexBot", 
		"19" => "Java/1.4.1_04", 
		"20" => "SiteBot", 
		"21" => "Exabot", 
		"22" => "AhrefsBot", 
		"23" => "MJ12bot", 
		"24" => "NetSeer crawler", 
		"25" => "TurnitinBot", 
		"26" => "magpie-crawler", 
		"27" => "Nutch Crawler", 
		"28" => "CMS Crawler", 
		"29" => "rogerbot", 
		"30" => "Domnutch", 
		"31" => "ssearch_bot", 
		"32" => "XoviBot", 
		"33" => "digincore", 
		"34" => "fr-crawler", 
		"35" => "SeznamBot", 
		"36" => "Seznam screenshot-generator", 
		"37" => "Facebot", 
		"38" => "facebookexternalhit"
	),
	'do_not_track_internal_ips' => array(

	),
	'link_shortener_url' => null,
	'cached_data_timeout' => '10',
	'batch_sleep_time' => 1,
	'batch_campaign_sleep_time' => false,
	'cors_restrict_domains' => 1,
	'cors_valid_domains' => array(

	),
	'rss_notification_url' => 'https://mautic.com/?feed=rss2&tag=notification',
	'api_enabled' => 0,
	'api_enable_basic_auth' => false,
	'api_oauth2_access_token_lifetime' => 60,
	'api_oauth2_refresh_token_lifetime' => 14,
	'api_batch_max_limit' => 200,
	'upload_dir' => '/var/www/html/mautic/app/../media/files',
	'max_size' => '100',
	'allowed_extensions' => array(
		"0" => "csv", 
		"1" => "doc", 
		"2" => "docx", 
		"3" => "epub", 
		"4" => "gif", 
		"5" => "jpg", 
		"6" => "jpeg", 
		"7" => "mpg", 
		"8" => "mpeg", 
		"9" => "mp3", 
		"10" => "odt", 
		"11" => "odp", 
		"12" => "ods", 
		"13" => "pdf", 
		"14" => "png", 
		"15" => "ppt", 
		"16" => "pptx", 
		"17" => "tif", 
		"18" => "tiff", 
		"19" => "txt", 
		"20" => "xls", 
		"21" => "xlsx", 
		"22" => "wav"
	),
	'campaign_time_wait_on_event_false' => 'PT1H',
	'mailer_return_path' => 'srinib@realmilk.co.in',
	'mailer_append_tracking_pixel' => 1,
	'mailer_convert_embed_images' => 0,
	'mailer_amazon_region' => 'email-smtp.us-east-1.amazonaws.com',
	'mailer_spool_msg_limit' => null,
	'mailer_spool_time_limit' => null,
	'mailer_spool_recover_timeout' => '900',
	'mailer_spool_clear_timeout' => '1800',
	'unsubscribe_text' => '<a href=\'|URL|\'>Unsubscribe</a> to no longer receive emails from us.',
	'webview_text' => '<a href=\'|URL|\'>Having trouble reading this email? Click here.</a>',
	'unsubscribe_message' => 'We are sorry to see you go! |EMAIL| will no longer receive emails from us. If this was by mistake, <a href=\'|URL|\'>click here to re-subscribe</a>.',
	'resubscribe_message' => '|EMAIL| has been re-subscribed. If this was by mistake, <a href=\'|URL|\'>click here to unsubscribe</a>.',
	'monitored_email' => array(
		"general" => array(
			"address" => "", 
			"host" => "", 
			"port" => "993", 
			"encryption" => "/ssl", 
			"user" => "srinib@acknotech.com", 
			"password" => ""
		), 
		"EmailBundle_bounces" => array(
			"address" => "", 
			"host" => "", 
			"port" => "993", 
			"encryption" => "/ssl", 
			"user" => "", 
			"password" => "", 
			"override_settings" => "", 
			"folder" => "", 
			"ssl" => "1"
		), 
		"EmailBundle_unsubscribes" => array(
			"address" => "", 
			"host" => "", 
			"port" => "993", 
			"encryption" => "/ssl", 
			"user" => "", 
			"password" => "", 
			"override_settings" => "", 
			"folder" => "", 
			"ssl" => "1"
		)
	),
	'mailer_is_owner' => 1,
	'default_signature_text' => 'Best regards, |FROM_NAME|',
	'email_frequency_number' => null,
	'email_frequency_time' => null,
	'show_contact_preferences' => 0,
	'show_contact_frequency' => 0,
	'show_contact_pause_dates' => 0,
	'show_contact_preferred_channels' => 0,
	'show_contact_categories' => 0,
	'show_contact_segments' => 0,
	'mailer_mailjet_sandbox' => 0,
	'mailer_mailjet_sandbox_default_mail' => null,
	'cat_in_page_url' => 0,
	'google_analytics' => null,
	'track_contact_by_ip' => 0,
	'track_by_fingerprint' => 0,
	'redirect_list_types' => array(
		"301" => "mautic.page.form.redirecttype.permanent", 
		"302" => "mautic.page.form.redirecttype.temporary"
	),
	'saml_idp_own_password' => null,
	'saml_idp_email_attribute' => 'EmailAddress',
	'saml_idp_username_attribute' => null,
	'saml_idp_firstname_attribute' => 'FirstName',
	'saml_idp_lastname_attribute' => 'LastName',
	'saml_idp_default_role' => 1,
	'webhook_start' => 0,
	'webhook_limit' => 1000,
	'webhook_log_max' => 10,
	'queue_mode' => 'immediate_process',
	'twitter_handle_field' => 'twitter',
);
